name: Deploy Wolfi Base Images
on:
  push:
    branches:
      - abc

jobs:
  deploy_py3-10:
      uses: ./.github/workflows/wolfi-base-image-builder.yaml
      with:
        file-path: ./wolfi/
        file-name: wolfi-python3-10-pip.yaml
        base-image-name: wolfi-python3-10-pip
        repo-name: jasaz/wolfi-python
        
        
        
    
