name: Deploy Wolfi Base Images
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    strategy:
      matrix:
        include:
          - file-name: wolfi-python3-12.yaml
            base-image-name: wolfi-python3-12
          - file-name: wolfi-python3-12-pip.yaml
            base-image-name: wolfi-python3-12-pip
          - file-name: wolfi-python3-13.yaml
            base-image-name: wolfi-python3-13
          - file-name: wolfi-python3-13-pip.yaml
            base-image-name: wolfi-python3-13-pip
          - file-name: wolfi-python3-14.yaml
            base-image-name: wolfi-python3-14
          - file-name: wolfi-python3-14-pip.yaml
            base-image-name: wolfi-python3-14-pip
    uses: ./.github/workflows/wolfi-base-image-builder.yaml
    with:
      file-path: ./wolfi/
      file-name: ${{ matrix.file-name }}
      base-image-name: ${{ matrix.base-image-name }}
      repo-name: wolfi-python
    secrets: inherit

